plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "db/cable_schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "config/environments/**/*"
    - "config/puma.rb"
    - "config/boot.rb"
    - "Gemfile"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Rails/SkipsModelValidations:
  Exclude:
    - "app/services/**/*"

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
